require('dotenv').config()
const mongoose = require('mongoose')
const Pet = require('./models/Pet')

const BASE = 'https://ftp.goit.study/img/pets/'

const pets = [
  {
    name: 'Golden Retriever Puppies',
    birthday: '10.01.2026',
    sex: 'Male',
    species: 'Dog',
    category: 'free',
    location: 'Kyiv',
    description: 'Adorable puppy looking for a loving home.',
    image: `${BASE}1.webp`,
    rating: 5,
    isPopular: true,
  },
  {
    name: 'Golden Retriever Puppies',
    birthday: '10.01.2026',
    sex: 'Female',
    species: 'Dog',
    category: 'free',
    location: 'Lviv',
    description: 'Adorable puppy looking for a loving home.',
    image: `${BASE}2.webp`,
    rating: 4,
    isPopular: true,
  },
  {
    name: 'Sphynx Cat',
    birthday: '15.02.2026',
    sex: 'Female',
    species: 'Cat',
    category: 'free',
    location: 'Odesa',
    description: 'Gorgeous Sphynx cat available for adoption.',
    image: `${BASE}23.webp`,
    rating: 9,
    isPopular: true,
  },
  {
    name: 'Canary Looking for a Home',
    birthday: '03.01.2026',
    sex: 'Male',
    species: 'Bird',
    category: 'free',
    location: 'Kharkiv',
    description: 'Sweet canary bird needs a loving family.',
    image: `${BASE}7.webp`,
    rating: 3,
    isPopular: true,
  },
  {
    name: 'Playful Border Collie',
    birthday: '20.02.2026',
    sex: 'Male',
    species: 'Dog',
    category: 'free',
    location: 'Dnipro',
    description: 'Energetic and intelligent Border Collie looking for an active family.',
    image: `${BASE}26.webp`,
    rating: 2,
    isPopular: false,
  },
  {
    name: 'Rescued Mixed Breed Pup',
    birthday: '05.03.2026',
    sex: 'Female',
    species: 'Dog',
    category: 'free',
    location: 'Zaporizhzhia',
    description: 'Rescued pup looking for a forever home.',
    image: `${BASE}39.webp`,
    rating: 2,
    isPopular: false,
  },
  {
    name: 'Lost Macaw',
    birthday: '11.03.2026',
    sex: 'Unknown',
    species: 'Bird',
    category: 'lost',
    location: 'Kyiv',
    description: 'Colorful macaw lost near the city center. Please contact if found.',
    image: `${BASE}48.webp`,
    rating: 1,
    isPopular: false,
  },
  {
    name: 'Found Poison Dart Frog',
    birthday: '08.03.2026',
    sex: 'Unknown',
    species: 'Frog',
    category: 'found',
    location: 'Lviv',
    description: 'Found this frog near the botanical garden.',
    image: `${BASE}25.webp`,
    rating: 1,
    isPopular: false,
  },
  {
    name: 'Ant Farm Giveaway',
    birthday: '01.03.2026',
    sex: 'Unknown',
    species: 'Insect',
    category: 'free',
    location: 'Odesa',
    description: 'Free ant farm with a thriving colony. Educational and fascinating!',
    image: `${BASE}13.webp`,
    rating: 3,
    isPopular: false,
  },
  {
    name: 'Beehive Giveaway',
    birthday: '14.03.2026',
    sex: 'Unknown',
    species: 'Insect',
    category: 'free',
    location: 'Kharkiv',
    description: 'Healthy beehive free to a good beekeeper.',
    image: `${BASE}51.webp`,
    rating: 1,
    isPopular: false,
  },
  {
    name: 'Found Capuchin Monkey',
    birthday: '18.03.2026',
    sex: 'Male',
    species: 'Monkey',
    category: 'found',
    location: 'Dnipro',
    description: 'Found this friendly monkey near the park.',
    image: `${BASE}12.webp`,
    rating: 12,
    isPopular: true,
  },
  {
    name: 'Found Monarch Butterfly',
    birthday: '20.03.2026',
    sex: 'Unknown',
    species: 'Insect',
    category: 'found',
    location: 'Kyiv',
    description: 'Beautiful butterfly found in the garden.',
    image: `${BASE}9.webp`,
    rating: 2,
    isPopular: false,
  },
]

mongoose.connect(process.env.MONGO_URI).then(async () => {
  await Pet.deleteMany({})
  await Pet.insertMany(pets)
  console.log(`✅ ${pets.length} pets seeded with real images`)
  mongoose.disconnect()
}).catch(err => {
  console.error(err.message)
  process.exit(1)
})
