/* The sample notices. They are examples: the stories are made up, and none of
   the animals in the photographs is lost. The photographs are real ones from
   Wikimedia Commons, credited on the credits page. Every moment is kept as
   "so many days ago", so the board never goes stale. */

import { samplePhoto } from './photos';
import type { Ago, Kind, Notice, Sex, Sighting, Species } from './types';

interface Sample {
  id: number;
  kind: Kind;
  species: Species;
  name?: string;
  title: string;
  sex?: Sex;
  age?: string;
  marks: string;
  district: string;
  hood: string;
  place: string;
  ago: [days: number, clock: string];
  text: string;
  photo: string;
  by: string;
  seen?: [days: number, clock: string, where: string, note: string, by: string][];
  home?: [after: number, note: string];
}

const SAMPLES: Sample[] = [
  /* ---------- lost ---------- */
  {
    id: 2058,
    kind: 'lost',
    species: 'cat',
    name: 'Çorap',
    title: 'Black and white cat',
    sex: 'male',
    age: '4 years',
    marks: 'White bib, four white feet, a black spot beside the nose. Neutered, no collar.',
    district: 'Beyoğlu',
    hood: 'Cihangir',
    place: 'Akarsu Yokuşu, by the street door',
    ago: [0, '07:50'],
    text: 'He slipped out when the door was held open for a delivery. He is an indoor cat and will be frightened: he is probably under a car or in a basement stairwell close by. Please look before you call him, he runs from strangers.',
    photo: 'corap',
    by: 'Deniz',
  },
  {
    id: 2055,
    kind: 'lost',
    species: 'dog',
    name: 'Karamel',
    title: 'Brindle dog',
    sex: 'male',
    age: '3 years',
    marks: 'Dark brindle coat, patterned red collar, white patch on the chest. Microchipped.',
    district: 'Kadıköy',
    hood: 'Moda',
    place: 'near the tea garden on the shore path',
    ago: [2, '21:40'],
    text: 'He took fright at fireworks and pulled out of his lead. He is gentle but shy, and he will back away if you walk at him. Please do not chase: sit down, speak quietly, and tell us where you are.',
    photo: 'karamel',
    by: 'Elif',
    seen: [
      [2, '22:15', 'Moda Caddesi, outside the bakery', 'Running towards the tram stop, lead trailing.', 'Onur'],
      [1, '06:40', 'Yoğurtçu Parkı, by the stream', 'Drinking from the stream. Ran when a jogger came close.', 'Selin'],
      [0, '08:05', 'Kurbağalıdere, under the footbridge', 'Lying under the bridge. Same collar. Still there at ten past.', 'Mert'],
    ],
  },
  {
    id: 2053,
    kind: 'lost',
    species: 'bird',
    name: 'Mavi',
    title: 'Turquoise budgerigar',
    age: '2 years',
    marks: 'Turquoise body, white face with black bars on the head. A metal ring on the left leg.',
    district: 'Bakırköy',
    hood: 'Yeşilköy',
    place: 'a third-floor balcony on İstasyon Caddesi',
    ago: [1, '16:20'],
    text: 'He flew out through a balcony window. An escaped budgerigar often stays close for the first days, in a tree or on a balcony within a few streets. He comes to the sound of his own cage bell. If he lands near you, a towel over him is the safest way to hold him.',
    photo: 'mavi',
    by: 'Aylin',
    seen: [[0, '09:30', 'the plane trees by Yeşilköy station', 'A blue-green budgie with the sparrows, high up.', 'Kerem']],
  },
  {
    id: 2049,
    kind: 'lost',
    species: 'cat',
    name: 'Boncuk',
    title: 'White cat with patches',
    sex: 'female',
    age: '3 years',
    marks: 'White, with a grey patch on the back and ginger on the head. Green eyes. Black collar with a bell.',
    district: 'Şişli',
    hood: 'Nişantaşı',
    place: 'the back garden of a block on Atiye Sokak',
    ago: [3, '23:10'],
    text: 'She goes into the garden every evening and has always come back by midnight. She knows her name and the sound of her food tin. Please check sheds, garages and car engines: she likes warm, closed places.',
    photo: 'boncuk',
    by: 'Zeynep',
    seen: [
      [2, '07:20', 'Maçka Parkı, upper gate', 'A white cat with a bell, sitting on the wall.', 'Burak'],
      [1, '19:45', 'a courtyard on Bronz Sokak', 'Heard a bell, saw her on a first-floor ledge.', 'İpek'],
    ],
  },
  {
    id: 2046,
    kind: 'lost',
    species: 'dog',
    name: 'Paşa',
    title: 'Small long-haired dog',
    sex: 'male',
    age: '9 years',
    marks: 'Black, tan and white, long ears, grey round the muzzle. He is hard of hearing. Blue harness.',
    district: 'Beşiktaş',
    hood: 'Bebek',
    place: 'Bebek Parkı, the lawn by the pier',
    ago: [4, '18:30'],
    text: 'He wandered off while we were talking and does not hear when he is called. He is old and slow and will not have gone far on his own, so somebody may have picked him up. He needs a tablet every day for his heart.',
    photo: 'pasa',
    by: 'Cem',
  },
  {
    id: 2041,
    kind: 'lost',
    species: 'cat',
    name: 'Pamuk',
    title: 'White cat with odd eyes',
    sex: 'female',
    age: '2 years',
    marks: 'All white, long tail. One blue eye and one green. She is deaf, as white cats with a blue eye often are.',
    district: 'Beşiktaş',
    hood: 'Arnavutköy',
    place: 'the steps above Bebek-Arnavutköy Caddesi',
    ago: [6, '22:00'],
    text: 'She cannot hear traffic or her name. She is used to people and will come to a hand held low. If you see a white cat on these streets, please look at her eyes before you walk on.',
    photo: 'pamuk',
    by: 'Naz',
    seen: [[3, '13:10', 'the fish restaurants on the shore road', 'A white cat being fed scraps. Did not look up when called.', 'Hakan']],
  },
  {
    id: 2038,
    kind: 'lost',
    species: 'cat',
    name: 'Limon',
    title: 'Black and white kitten',
    sex: 'female',
    age: '5 months',
    marks: 'Black back, white face and legs, pink pads with black spots. Too young for a collar.',
    district: 'Fatih',
    hood: 'Balat',
    place: 'a ground-floor window on Vodina Caddesi',
    ago: [5, '20:15'],
    text: 'The window was open a hand’s width and she went through it. She has never been outside. She is small enough to be under a step or inside a wall, and she answers a rattled bag of treats.',
    photo: 'limon',
    by: 'Yusuf',
  },
  {
    id: 2036,
    kind: 'lost',
    species: 'cat',
    name: 'Zeytin',
    title: 'Black cat',
    sex: 'male',
    age: '6 years',
    marks: 'All black, yellow eyes, a notch out of the right ear. Neutered and microchipped.',
    district: 'Kadıköy',
    hood: 'Yeldeğirmeni',
    place: 'the roof terrace of a block on Karakolhane Caddesi',
    ago: [8, '02:00'],
    text: 'He goes over the roofs at night and has been gone for longer than he ever has. Black cats are hard to tell apart: his ear and his chip are what identify him. Any vet can read the chip.',
    photo: 'zeytin',
    by: 'Ece',
  },
  {
    id: 2033,
    kind: 'lost',
    species: 'rabbit',
    name: 'Tarçın',
    title: 'Cinnamon rabbit',
    sex: 'female',
    age: '1 year',
    marks: 'Reddish-brown coat, upright ears, white under the tail. Tame; she can be picked up.',
    district: 'Kadıköy',
    hood: 'Erenköy',
    place: 'a garden on Ethem Efendi Caddesi',
    ago: [7, '11:00'],
    text: 'She dug under the fence. Rabbits stay near cover and come out at dawn and dusk, so the best time to look is early. Please check under hedges and garden sheds along the street.',
    photo: 'tarcin',
    by: 'Defne',
  },
  {
    id: 2030,
    kind: 'lost',
    species: 'cat',
    name: 'Duman',
    title: 'Grey cat',
    sex: 'male',
    age: '5 years',
    marks: 'Solid blue-grey coat, orange eyes, heavy build.',
    district: 'Üsküdar',
    hood: 'Kuzguncuk',
    place: 'İcadiye Caddesi, near the old bakery',
    ago: [12, '19:30'],
    text: 'He got out during a move and did not know the street.',
    photo: 'duman',
    by: 'Kaan',
    seen: [
      [11, '08:00', 'the allotment gardens', 'A big grey cat asleep in a wheelbarrow.', 'Gül'],
      [10, '21:30', 'the allotment gardens, the far shed', 'Under the shed. Came out for sardines.', 'Kaan'],
    ],
    home: [3, 'Two neighbours saw him in the allotments on the same morning. He was under a shed, forty metres from the door he went out of.'],
  },
  {
    id: 2027,
    kind: 'lost',
    species: 'dog',
    name: 'Fındık',
    title: 'Sandy dog with a leather collar',
    sex: 'male',
    age: '7 years',
    marks: 'Sandy and white coat, worn brown leather collar, grey muzzle.',
    district: 'Sarıyer',
    hood: 'Emirgan',
    place: 'the car park at the gate of Emirgan Korusu',
    ago: [15, '10:20'],
    text: 'He jumped out of the car as the boot was opened and ran into the woods.',
    photo: 'findik',
    by: 'Tolga',
    seen: [[11, '17:00', 'İstinye shore, by the boatyard', 'A sandy dog with a leather collar being fed by the fishermen.', 'Sevgi']],
    home: [5, 'A sighting from İstinye, the next bay up the shore. The fishermen had been feeding him for three days.'],
  },

  /* ---------- found ---------- */
  {
    id: 2057,
    kind: 'found',
    species: 'cat',
    title: 'Ginger long-haired cat',
    sex: 'unknown',
    marks: 'Long ginger coat, matted along the back, flat face. No collar. Very tame.',
    district: 'Kadıköy',
    hood: 'Yeldeğirmeni',
    place: 'the bus stop on Rıhtım Caddesi',
    ago: [0, '08:15'],
    text: 'Asleep on a bag at the bus stop and still there an hour later. A long-haired cat with a coat in this state has been somebody’s and has been out for a while. I have taken the cat home and will ask a vet to look for a chip.',
    photo: 'persian',
    by: 'Seda',
  },
  {
    id: 2054,
    kind: 'found',
    species: 'cat',
    title: 'Young tabby cat',
    sex: 'male',
    age: 'about 4 months',
    marks: 'Grey-brown tabby, white chin, very large ears. No collar, no ear tip.',
    district: 'Beşiktaş',
    hood: 'Ihlamur',
    place: 'the car park behind Ihlamur Kasrı',
    ago: [1, '09:30'],
    text: 'Under a motorbike, crying. He is clean, used to being handled and walked straight into a carrier, so he is not a street kitten. He is with me and eating well.',
    photo: 'tabby-kitten',
    by: 'Arda',
  },
  {
    id: 2051,
    kind: 'found',
    species: 'dog',
    title: 'Tan and black dog',
    sex: 'female',
    age: 'young adult',
    marks: 'Tan with a black saddle, upright ears with folded tips, white toes. No collar, no ear tag.',
    district: 'Maltepe',
    hood: 'Maltepe shore',
    place: 'the cycle path along the shore park',
    ago: [2, '07:00'],
    text: 'She has followed the morning runners for two days and sits when she is told to. She has no municipal ear tag, which a registered street dog would have. She is still on the shore: I cannot take her in.',
    photo: 'tan-dog',
    by: 'Barış',
  },
  {
    id: 2047,
    kind: 'found',
    species: 'cat',
    title: 'Long-haired tabby cat',
    sex: 'unknown',
    marks: 'Dark tabby, long coat, white bib and feet, a thick ruff. No collar.',
    district: 'Kadıköy',
    hood: 'Bostancı',
    place: 'the rocks below the sea wall',
    ago: [3, '13:25'],
    text: 'Sitting on the rocks every afternoon this week. The coat is brushed and clean, which a street cat’s is not at that length. The cat lets you come within a step and no closer.',
    photo: 'longhair',
    by: 'Nil',
  },
  {
    id: 2044,
    kind: 'found',
    species: 'dog',
    title: 'Old cream dog',
    sex: 'male',
    age: 'old',
    marks: 'Cream coat, drop ears, cloudy eyes. Limps on the left hind leg. No collar.',
    district: 'Kadıköy',
    hood: 'Fenerbahçe',
    place: 'the pavement outside the marina gate',
    ago: [4, '16:40'],
    text: 'He has lain outside the marina since Monday and does not get up for food. The guards say he is new here. He is calm and lets himself be stroked. The municipal vet has been asked to look at his leg.',
    photo: 'old-dog',
    by: 'Hande',
  },
  {
    id: 2040,
    kind: 'found',
    species: 'cat',
    title: 'Tabby and white kitten',
    sex: 'female',
    age: 'about 8 weeks',
    marks: 'Tabby back and tail, white face, chest and legs. A dark smudge on the nose.',
    district: 'Fatih',
    hood: 'Fener',
    place: 'a courtyard off Yıldırım Caddesi',
    ago: [5, '12:00'],
    text: 'Alone in the courtyard for a day with no mother coming back. She is eating on her own. She is with a foster for now; if she is yours, a photograph of her with her litter is all we need.',
    photo: 'courtyard-kitten',
    by: 'Oya',
  },
  {
    id: 2034,
    kind: 'found',
    species: 'cat',
    title: 'Black and white cat',
    sex: 'male',
    age: 'adult',
    marks: 'Black with a white blaze, white chest and feet. Neutered, no ear tip, no collar.',
    district: 'Beyoğlu',
    hood: 'Galata',
    place: 'a stairwell on Serdar-ı Ekrem Sokak',
    ago: [9, '23:40'],
    text: 'In our stairwell for two nights, crying at every door.',
    photo: 'tuxedo',
    by: 'Lale',
    home: [1, 'His owner knew him from the photograph within a day: he had gone out of a window three streets away.'],
  },

  /* ---------- looking for a home ---------- */
  {
    id: 2056,
    kind: 'adopt',
    species: 'dog',
    name: 'Fıstık',
    title: 'Cream dog',
    sex: 'male',
    age: '2 years',
    marks: 'Cream coat, feathered ears, brown eyes. Neutered, vaccinated, microchipped.',
    district: 'Fatih',
    hood: 'Balat',
    place: 'in a foster home',
    ago: [1, '10:00'],
    text: 'He was left tied to a railing in spring. In his foster home he has lived with two children and a cat and has not put a foot wrong. He walks well on a lead and sleeps through the night. He needs a home where somebody is in for part of the day.',
    photo: 'fistik',
    by: 'Merve',
  },
  {
    id: 2052,
    kind: 'adopt',
    species: 'dog',
    name: 'Kestane',
    title: 'Brown puppy',
    sex: 'female',
    age: '4 months',
    marks: 'Chestnut coat, black muzzle, ears that have not decided which way to go. First vaccinations done.',
    district: 'Ümraniye',
    hood: 'Çakmak',
    place: 'in a foster home',
    ago: [2, '14:00'],
    text: 'One of three found in a building site. She will be a medium-sized dog. She is the quiet one of the litter and watches before she joins in. Her brother has a home already.',
    photo: 'kestane',
    by: 'Sinan',
  },
  {
    id: 2050,
    kind: 'adopt',
    species: 'dog',
    name: 'Aslan',
    title: 'Kangal-cross puppy',
    sex: 'male',
    age: '5 months',
    marks: 'Pale coat, black mask and ears. He will be a very large dog. Vaccinated.',
    district: 'Beykoz',
    hood: 'Riva',
    place: 'at a smallholding',
    ago: [3, '09:00'],
    text: 'He needs a garden and somebody who knows large dogs: a Kangal cross is a guardian, not a flat dog, and at a year old he will weigh more than most people can lift. With that said plainly, he is calm, steady and very gentle with the hens.',
    photo: 'aslan',
    by: 'Recep',
  },
  {
    id: 2048,
    kind: 'adopt',
    species: 'cat',
    name: 'Sarman',
    title: 'Ginger tom',
    sex: 'male',
    age: 'about 3 years',
    marks: 'Ginger tabby, cream chest, a tipped left ear: he has been neutered by the municipality.',
    district: 'Beyoğlu',
    hood: 'Kabataş',
    place: 'on the pier wall',
    ago: [3, '17:35'],
    text: 'He has lived on the pier for two years and greets the ferry. He is as tame as a street cat gets and climbs into laps. The tea kiosk that feeds him is closing for the winter. He would suit a home with a balcony or a garden.',
    photo: 'sarman',
    by: 'Pınar',
  },
  {
    id: 2045,
    kind: 'adopt',
    species: 'cat',
    name: 'Lokum',
    title: 'Calico cat',
    sex: 'female',
    age: '1 year',
    marks: 'White with black and ginger patches, a ginger patch over the right eye. Spayed and vaccinated.',
    district: 'Kadıköy',
    hood: 'Göztepe',
    place: 'in a foster home',
    ago: [4, '11:30'],
    text: 'She came off the street with a litter, and the kittens have all gone to homes. She is the easiest cat I have fostered: she uses her tray, her post and her own bed. She would rather be the only cat.',
    photo: 'lokum',
    by: 'Ayşe',
  },
  {
    id: 2043,
    kind: 'adopt',
    species: 'cat',
    name: 'Portakal',
    title: 'Ginger and white kitten',
    sex: 'male',
    age: '3 months',
    marks: 'White, with ginger on the back, tail and ears. First vaccination done.',
    district: 'Üsküdar',
    hood: 'Çengelköy',
    place: 'in a foster home',
    ago: [4, '15:10'],
    text: 'Found in a rain gutter at three weeks and raised by hand, so he thinks people are cats. He plays hard and sleeps harder. A kitten this age does best with another young cat for company.',
    photo: 'portakal',
    by: 'Emre',
  },
  {
    id: 2039,
    kind: 'adopt',
    species: 'cat',
    name: 'Gölge',
    title: 'Grey tabby',
    sex: 'male',
    age: 'about 2 years',
    marks: 'Silver-grey tabby, green eyes, striped legs. Neutered, ear tipped.',
    district: 'Beyoğlu',
    hood: 'Kabataş',
    place: 'on the benches by the ferry',
    ago: [6, '17:45'],
    text: 'Sarman’s neighbour on the pier, and the shyer of the two. It takes him a few days to trust a hand, and after that he follows it. He has been fed by the same tea seller for a year, who would like to know he is indoors before the kiosk shuts.',
    photo: 'golge',
    by: 'Pınar',
  },
  {
    id: 2037,
    kind: 'adopt',
    species: 'cat',
    name: 'Mırmır',
    title: 'Tabby cat',
    sex: 'female',
    age: '4 years',
    marks: 'Brown tabby, amber eyes, a kink at the tip of the tail. Spayed.',
    district: 'Fatih',
    hood: 'Sultanahmet',
    place: 'at a café terrace',
    ago: [7, '12:20'],
    text: 'She has held court on this terrace for four years. The café is closing at the end of the season and nobody is taking on the lease. She is used to noise, strangers and being photographed, and she likes a cushion of her own.',
    photo: 'mirmir',
    by: 'Hasan',
  },
  {
    id: 2035,
    kind: 'adopt',
    species: 'rabbit',
    name: 'Pofuduk',
    title: 'Grey rabbit',
    sex: 'male',
    age: '1 year',
    marks: 'Soft grey coat, upright ears. Neutered, litter-trained.',
    district: 'Ataşehir',
    hood: 'Küçükbakkalköy',
    place: 'with his owner',
    ago: [8, '19:00'],
    text: 'We are moving abroad and cannot take him. He lives loose in the flat, comes when the fridge opens and has never chewed a cable he was not offered. His hutch, run and a month of hay come with him.',
    photo: 'pofuduk',
    by: 'İrem',
  },
  {
    id: 2032,
    kind: 'adopt',
    species: 'cat',
    name: 'Çakıl',
    title: 'Black and white cat',
    sex: 'female',
    age: '6 years',
    marks: 'Black, with a white chin, chest and toes. Spayed, vaccinated, indoor only.',
    district: 'Şişli',
    hood: 'Kurtuluş',
    place: 'with a neighbour',
    ago: [10, '10:40'],
    text: 'Her owner has gone into care and cannot keep her. She has lived in one flat all her life with one person, and she wants exactly that again: a quiet home, a windowsill, and no other animals.',
    photo: 'cakil',
    by: 'Sibel',
  },
  {
    id: 2029,
    kind: 'adopt',
    species: 'dog',
    name: 'Badem',
    title: 'Brown puppy with a black mask',
    sex: 'male',
    age: '4 months',
    marks: 'Chestnut coat, black mask, one ear up and one down.',
    district: 'Ümraniye',
    hood: 'Çakmak',
    place: 'in a foster home',
    ago: [14, '14:00'],
    text: 'Kestane’s brother, and the loud one of the litter.',
    photo: 'badem',
    by: 'Sinan',
    home: [9, 'Adopted by a family in Çekmeköy with a garden and an older dog to teach him manners.'],
  },
];

const ago = ([days, clock]: [number, string]): Ago => ({ days, clock });

/** The sample notices, newest first. */
export const SEED: Notice[] = SAMPLES.map((sample) => ({
  id: `YV-${sample.id}`,
  kind: sample.kind,
  home: sample.home ? { at: 0, after: sample.home[0], note: sample.home[1] } : null,
  species: sample.species,
  name: sample.name ?? null,
  title: sample.title,
  sex: sample.sex ?? 'unknown',
  age: sample.age ?? null,
  marks: sample.marks,
  district: sample.district,
  hood: sample.hood,
  place: sample.place,
  at: 0,
  ago: ago(sample.ago),
  text: sample.text,
  photo: samplePhoto(sample.photo),
  contact: { name: sample.by },
  sightings: (sample.seen ?? []).map(
    ([days, clock, where, note, by], index): Sighting => ({ id: `YV-${sample.id}-${index + 1}`, at: 0, ago: { days, clock }, where, note, by }),
  ),
  sample: true,
})).sort((a, b) => a.ago!.days - b.ago!.days || b.ago!.clock.localeCompare(a.ago!.clock));

/** A notice's place in an address: yv-2041. */
export const pathOf = (id: string) => `/notices/${id.toLowerCase()}/`;
export const seedById = (id: string) => SEED.find((notice) => notice.id.toLowerCase() === id.toLowerCase());
